### ISSUE TITLE
From digit count in two hex codes

### ISSUE THREAD

**Issue by acjbizar** [pixelbrackets/ral-color-chart#1]
RAL 6024 and RAL 6029 have a hex code associated that is four digits long. I don’t know how this list was compiled, but it appears to me there is a `str_pad($hex, 6, '0', STR_PAD_LEFT)` or equivalent missing in the process. I could do a pull request and fix the two codes, but it’s probably better to fix the thing that generated this list, would you agree?

**Comment by pixelbrackets** [comment]
I remember that I build a mandala script to generate this list, meaning I threw it away after it served its purpose.

Yeah, the listed items omnit the two leading zeros. However, other colors like RAL 6036 do contain two leading zeros. 

Anyways, I fixed the code and will publish a new version asap. Thanks for the report!

**Comment by pixelbrackets** [comment]
Fixed in version [2.0.2](https://packagist.org/packages/pixelbrackets/ral-color-chart#2.0.2) 

Thanks a lot for the report @acjbizar

**Comment by acjbizar** [comment]
> Yeah, the listed items omnit the two leading zeros. However, other colors like RAL 6036 do contain two leading zeros.

Ah, I had missed that. That’s curious.

> Anyways, I fixed the code and will publish a new version asap. Thanks for the report!

You’re welcome. Thanks for the fix!
